# Generated by Django 4.1.5 on 2023-01-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(unique=True, verbose_name='Telegram')),
                ('facebook', models.URLField(unique=True, verbose_name='Facebook')),
                ('instagram', models.URLField(unique=True, verbose_name='Instagram')),
                ('career', models.URLField(unique=True, verbose_name='Habr Career')),
                ('twitter', models.URLField(unique=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(unique=True, verbose_name='LinkedIn')),
                ('phone', models.CharField(max_length=200, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='Адрес')),
            ],
        ),
    ]
