# Generated by Django 4.1.5 on 2023-01-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Рекрутер', 'Рекрутер'), ('Директор', 'Директор'), ('Организация', 'Организация'), ('Техподдержка', 'Техподдержка')], default='Рекрутер', max_length=500, verbose_name='Должность')),
                ('name', models.CharField(default='Неопознанный member', max_length=500, verbose_name='Фамилия Имя')),
                ('telegram', models.CharField(max_length=200, unique=True, verbose_name='Telegram')),
                ('facebook', models.URLField(default='https://facebook.com/', verbose_name='Facebook')),
                ('instagram', models.URLField(default='https://instagram.com/', verbose_name='Instagram')),
                ('career', models.URLField(default='https://career.habr.com/', verbose_name='Habr Career')),
                ('twitter', models.URLField(default='https://twitter.com/', verbose_name='Twitter')),
                ('linkedin', models.URLField(default='https://linkedin.com/in/', verbose_name='LinkedIn')),
                ('phone', models.CharField(default='+375', max_length=200, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('address', models.CharField(default='Минск, ', max_length=200, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Emplouee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Рекрутер', 'Рекрутер'), ('Директор', 'Директор'), ('Организация', 'Организация'), ('Техподдержка', 'Техподдержка')], default='Рекрутер', max_length=500, verbose_name='Должность')),
                ('name', models.CharField(default='Неопознанный member', max_length=500, verbose_name='Фамилия Имя')),
                ('activity', models.CharField(choices=[('Действующий сотрудник', 'Действующий сотрудник'), ('Уволенный', 'Уволенный')], max_length=500, verbose_name='Активность')),
            ],
        ),
    ]
