# Generated by Django 4.1.5 on 2023-01-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='default_status',
            field=models.BooleanField(default=0, verbose_name='Основной'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title',
            field=models.CharField(default='Организация', max_length=200, verbose_name='Должность'),
        ),
    ]
