# Generated by Django 4.1.5 on 2023-01-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contacts_address_alter_contacts_career_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='telegramurl',
            field=models.URLField(default='https://t.me/', verbose_name='Telegram URL'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram',
            field=models.CharField(max_length=200, verbose_name='Telegram'),
        ),
    ]
