# Generated by Django 4.1.5 on 2023-01-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contacts_telegramurl_alter_contacts_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='telegramurl',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.CharField(choices=[('Рекрутер', 'Рекрутер'), ('Директор', 'Директор'), ('Организация', 'Организация'), ('Техподдержка', 'Техподдержка')], default='Рекрутер', max_length=500, verbose_name='Должность'),
        ),
    ]
