# Generated by Django 4.1.5 on 2023-01-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_contacts_default_status_contacts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default='+375', max_length=200, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram',
            field=models.CharField(max_length=200, unique=True, verbose_name='Telegram'),
        ),
    ]
