# Generated by Django 4.1.5 on 2023-01-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contacts_phone_alter_contacts_telegram'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
