# Generated by Django 4.1.5 on 2023-01-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_rename_contacts_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplouee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Рекрутер', 'Рекрутер'), ('Директор', 'Директор'), ('Организация', 'Организация'), ('Техподдержка', 'Техподдержка')], default='Рекрутер', max_length=500, verbose_name='Должность')),
                ('name', models.CharField(default='Неопознанный member', max_length=500, verbose_name='Фамилия Имя')),
                ('activity', models.CharField(choices=[('Действующий сотрудник', 'Действующий сотрудник'), ('Уволенный', 'Уволенный')], max_length=500, verbose_name='Активность')),
            ],
        ),
    ]
