# Generated by Django 4.1.5 on 2023-01-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='grade',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead'), ('architect', 'Architect'), ('mentor', 'Mentor'), ('cto', 'CTO'), ('ceo', 'CEO')], default='middle', max_length=500, verbose_name='Грейд'),
            preserve_default=False,
        ),
    ]
