# Generated by Django 4.1.5 on 2023-01-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_vacancy_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BYN', 'BYN'), ('RYB', 'RYB')], max_length=500, verbose_name='Валюта'),
        ),
    ]
