# Generated by Django 4.1.5 on 2023-01-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_alter_vacancy_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='hot',
            field=models.BooleanField(default=0, verbose_name='Продвижение'),
        ),
    ]
