# Generated by Django 4.1.5 on 2023-01-11 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('post', models.TextField(verbose_name='Пост')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('blog_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('draft', models.BooleanField(default=0, verbose_name='Статус')),
            ],
        ),
    ]
