# Generated by Django 4.1.5 on 2023-01-14 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('status', models.BooleanField(default=0, verbose_name='Статус')),
            ],
        ),
    ]
