# Generated by Django 4.1.5 on 2023-01-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(default='--', max_length=50, null=True, verbose_name='Компания'),
        ),
    ]
