# Generated by Django 4.1.5 on 2023-01-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[('Ожидает ответа', 'Ожидает ответа'), ('Ответ направлен', 'Ответ направлен'), ('Пауза', 'Пауза'), ('Заявка закрыта', 'Заявка закрыта')], verbose_name='Статус'),
        ),
    ]
