# Generated by Django 4.1.5 on 2023-01-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('Беларусь', 'Беларусь'), ('Россия', 'Россия'), ('Казахстан', 'Казахстан'), ('США', 'США'), ('Польша', 'Польша'), ('Германия', 'Германия'), ('Великобритания', 'Великобритания'), ('Литва', 'Литва'), ('Латвия', 'Латвия')], default='Беларусь', max_length=500, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telegram',
            field=models.CharField(default='@', max_length=50, unique=True, verbose_name='Telegram'),
        ),
    ]
