# Generated by Django 4.1.5 on 2023-01-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидает ответа', 'Ожидает ответа'), ('Ответ направлен', 'Ответ направлен'), ('Пауза', 'Пауза'), ('Заявка закрыта', 'Заявка закрыта')], default='Ожидает ответа', max_length=50, verbose_name='Статус'),
        ),
    ]
