# Generated by Django 4.1.5 on 2023-01-14 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Последняя активность'),
        ),
    ]
