# Generated by Django 4.1.5 on 2023-01-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_price_currency_alter_tarif_currency_and_more'),
        ('orders', '0007_alter_order_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tarif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.tarif'),
            preserve_default=False,
        ),
    ]
