# Generated by Django 4.1.5 on 2023-01-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_tarif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tarif',
        ),
    ]
