# Generated by Django 4.1.5 on 2023-01-15 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('minimal_price', models.IntegerField(default=10, verbose_name='Минимальная цена')),
                ('unit', models.CharField(choices=[('год', 'Год'), ('месяц', 'Месяц'), ('вакансию', 'Вакансию'), ('команду', 'Команду'), ('сорсинг', 'Сорсинг')], max_length=40, verbose_name='Цена за')),
                ('description', models.TextField(verbose_name='Описание')),
                ('param_1', models.CharField(max_length=120, verbose_name='Параметр 1')),
                ('param_2', models.CharField(max_length=120, verbose_name='Параметр 2')),
                ('param_3', models.CharField(max_length=120, verbose_name='Параметр 3')),
                ('param_4', models.CharField(max_length=120, verbose_name='Параметр 4')),
                ('currency', models.CharField(choices=[('$', 'USD'), ('€', 'EUR'), ('BYN', 'BYN'), ('₽', 'RYB'), ('₿', 'BTC')], max_length=500, verbose_name='Валюта')),
                ('update_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('activity', models.CharField(choices=[('Неактивный', 'Неактивный'), ('Активный', 'Активный')], default='Неактивный', max_length=20, verbose_name='Активность')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametrs', models.CharField(choices=[('Разработчики', 'Разработчики'), ('Администраторы (DBA, System)', 'Администраторы (DBA, System)'), ('Аналитики, Project- / Product- менеджеры', 'Аналитики, Project- / Product- менеджеры'), ('ML инженеры, AI разработчики', 'ML инженеры, AI разработчики'), ('Дизайнеры, UI/UX', 'Дизайнеры, UI/UX'), ('Системные инженеры, *Ops инженеры', 'Системные инженеры, *Ops инженеры'), ('Архитекторы', 'Архитекторы'), ('Тестировщики, QA', 'Тестировщики, QA'), ('Digital, маркетологи', 'Digital, маркетологи'), ('Менеджер по развитию бизнеса', 'Менеджер по развитию бизнеса'), ('HR-менеджеры, рекрутеры', 'HR-менеджеры, рекрутеры'), ('Прочие специальности', 'Прочие специальности')], max_length=200, verbose_name='Направление')),
                ('grade', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=500, verbose_name='Грейд')),
                ('salary', models.IntegerField(default=150, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('$', 'USD'), ('€', 'EUR'), ('BYN', 'BYN'), ('₽', 'RYB'), ('₿', 'BTC')], default='USD', max_length=500, verbose_name='Валюта')),
                ('price_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('activity', models.CharField(choices=[('Неактивный', 'Неактивный'), ('Активный', 'Активный')], default='Неактивный', max_length=20, verbose_name='Активность')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tarif')),
            ],
            options={
                'unique_together': {('parametrs', 'tarif', 'grade')},
            },
        ),
    ]
