# Generated by Django 4.1.5 on 2023-01-14 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('color', models.CharField(max_length=10, verbose_name='Цвет публикации')),
                ('text', models.TextField(verbose_name='Описание')),
                ('salary_from', models.IntegerField(verbose_name='Вилка от')),
                ('salary_to', models.IntegerField(verbose_name='Вилка до')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BYN', 'BYN'), ('RYB', 'RYB')], max_length=500, verbose_name='Валюта')),
                ('grade', models.CharField(choices=[('trainee', 'Trainee'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead'), ('architect', 'Architect'), ('mentor', 'Mentor'), ('cto', 'CTO'), ('ceo', 'CEO')], max_length=500, verbose_name='Грейд')),
                ('stack', models.CharField(max_length=500, verbose_name='Технологии')),
                ('benefits', models.TextField(verbose_name='Предложение и бонусы')),
                ('vacancy_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('activity', models.BooleanField(default=0, verbose_name='Активность')),
                ('hot', models.BooleanField(default=0, verbose_name='Продвижение')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('color', models.CharField(max_length=10, verbose_name='Цвет публикации')),
                ('text', models.TextField(verbose_name='Описание')),
                ('salary_from', models.IntegerField(verbose_name='Вилка от')),
                ('salary_to', models.IntegerField(verbose_name='Вилка до')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BYN', 'BYN'), ('RYB', 'RYB')], max_length=500, verbose_name='Валюта')),
                ('grade', models.CharField(choices=[('trainee', 'Trainee'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead'), ('architect', 'Architect'), ('mentor', 'Mentor'), ('cto', 'CTO'), ('ceo', 'CEO')], max_length=500, verbose_name='Грейд')),
                ('stack', models.CharField(max_length=500, verbose_name='Технологии')),
                ('benefits', models.TextField(verbose_name='Предложение и бонусы')),
                ('vacancy_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('activity', models.BooleanField(default=0, verbose_name='Активность')),
                ('hot', models.BooleanField(default=0, verbose_name='Продвижение')),
            ],
        ),
    ]
