# Generated by Django 4.1.5 on 2023-01-15 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarif',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='hot',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='salary_from',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='salary_to',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='vacancy_date',
        ),
        migrations.AddField(
            model_name='tarif',
            name='minimal_price',
            field=models.IntegerField(default=10, verbose_name='Минимальная цена'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='param_1',
            field=models.CharField(default=1, max_length=120, verbose_name='Параметр 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarif',
            name='param_2',
            field=models.CharField(default=1, max_length=120, verbose_name='Параметр 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarif',
            name='param_3',
            field=models.CharField(default=1, max_length=120, verbose_name='Параметр 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarif',
            name='param_4',
            field=models.CharField(default=1, max_length=120, verbose_name='Параметр 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarif',
            name='unit',
            field=models.CharField(default=1, max_length=40, verbose_name='Цена за'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarif',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BYN', 'BYN'), ('RYB', 'RYB'), ('BTC', 'BTC')], max_length=500, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BYN', 'BYN'), ('RYB', 'RYB'), ('BTC', 'BTC')], max_length=500, verbose_name='Валюта'),
        ),
    ]
