# Generated by Django 4.1.5 on 2023-01-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_tarif_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
