# Generated by Django 4.1.5 on 2023-01-15 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_tarif_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='color',
        ),
        migrations.AddField(
            model_name='price',
            name='tarif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.tarif'),
            preserve_default=False,
        ),
    ]
