# Generated by Django 4.1.5 on 2023-01-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_tarif_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='activity',
            field=models.CharField(choices=[('Неактивный', 'Неактивный'), ('Активный', 'Активный')], default='Неактивный', max_length=20, verbose_name='Активность'),
        ),
    ]
