# Generated by Django 4.1.5 on 2023-01-15 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_tarif_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='price',
            name='hot',
        ),
        migrations.RemoveField(
            model_name='price',
            name='salary_from',
        ),
        migrations.RemoveField(
            model_name='price',
            name='salary_to',
        ),
        migrations.RemoveField(
            model_name='price',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='price',
            name='text',
        ),
        migrations.RemoveField(
            model_name='price',
            name='title',
        ),
        migrations.RemoveField(
            model_name='price',
            name='vacancy_date',
        ),
        migrations.AddField(
            model_name='price',
            name='parametrs',
            field=models.CharField(choices=[('Разработчики', 'Разработчики'), ('Администраторы (DBA, System)', 'Администраторы (DBA, System)'), ('Аналитики, Project- / Product- менеджеры', 'Аналитики, Project- / Product- менеджеры'), ('ML инженеры, AI разработчики', 'ML инженеры, AI разработчики'), ('Дизайнеры, UI/UX', 'Дизайнеры, UI/UX'), ('Системные инженеры, *Ops инженеры', 'Системные инженеры, *Ops инженеры'), ('Архитекторы', 'Архитекторы'), ('Тестировщики, QA', 'Тестировщики, QA'), ('Digital, маркетологи', 'Digital, маркетологи'), ('Менеджер по развитию бизнеса', 'Менеджер по развитию бизнеса'), ('HR-менеджеры, рекрутеры', 'HR-менеджеры, рекрутеры'), ('Прочие специальности', 'Прочие специальности')], default=1, max_length=200, unique=True, verbose_name='Направление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='price_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='price',
            name='salary',
            field=models.IntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='activity',
            field=models.CharField(choices=[('Неактивный', 'Неактивный'), ('Активный', 'Активный')], default='Неактивный', max_length=20, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='price',
            name='grade',
            field=models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=500, verbose_name='Грейд'),
        ),
    ]
