# Generated by Django 4.1.5 on 2023-01-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_price_benefits_remove_price_hot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='parametrs',
            field=models.CharField(choices=[('Разработчики', 'Разработчики'), ('Администраторы (DBA, System)', 'Администраторы (DBA, System)'), ('Аналитики, Project- / Product- менеджеры', 'Аналитики, Project- / Product- менеджеры'), ('ML инженеры, AI разработчики', 'ML инженеры, AI разработчики'), ('Дизайнеры, UI/UX', 'Дизайнеры, UI/UX'), ('Системные инженеры, *Ops инженеры', 'Системные инженеры, *Ops инженеры'), ('Архитекторы', 'Архитекторы'), ('Тестировщики, QA', 'Тестировщики, QA'), ('Digital, маркетологи', 'Digital, маркетологи'), ('Менеджер по развитию бизнеса', 'Менеджер по развитию бизнеса'), ('HR-менеджеры, рекрутеры', 'HR-менеджеры, рекрутеры'), ('Прочие специальности', 'Прочие специальности')], max_length=200, verbose_name='Направление'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('parametrs', 'tarif')},
        ),
    ]
