# Generated by Django 4.1.5 on 2023-01-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_price_parametrs_alter_price_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('parametrs', 'tarif', 'grade')},
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BYN', 'BYN'), ('RYB', 'RYB'), ('BTC', 'BTC')], default='USD', max_length=500, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='price',
            name='salary',
            field=models.IntegerField(default=150, verbose_name='Цена'),
        ),
    ]
