# Generated by Django 4.1.5 on 2023-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_price_currency_alter_tarif_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='update_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата обновления'),
        ),
    ]
