# Generated by Django 4.1.5 on 2023-01-15 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_alter_price_price_date_alter_tarif_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
    ]
